---

- name: Remove old Docker things
  apt: name={{item}} state=absent
  with_items:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc


- name: Allow apt to install over https
  apt: name={{item}} state=present
  with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common

- name: Add Docker Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

#- name: update apt cache
#  apt:
#    update_cache: yes

- name: Install docker
  apt: name={{item}} state=present
  with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

- name: Install docker-py
  pip:
    name: docker-compose

- name: Download docker compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Allow docker compose to run
  shell: chmod +x /usr/local/bin/docker-compose
