---

- name: Remove MyT MyTApplication
  file:
    path: /opt/MyTApplication
    state: absent

- name: Pull MyT git repo
  git:
    repo: https://github.com/Daemon-Macklin/MyTPlatformDataProcessingContainer
    dest: /opt/MyTApplication

- name: Pull tls-gen repo
  git:
    repo: https://github.com/michaelklishin/tls-gen.git
    dest: /opt/tls-gen
  when: rabbitmqTLS == "true"

- name: Generate tls keys
  command: make
  args:
    chdir: /opt/tls-gen/basic
  when: rabbitmqTLS == "true"

- name: Create file for tls keys
  file:
    path: /opt/MyTApplication/cert_rabbitmq
    state: directory
  when: rabbitmqTLS == "true"

- name: Get cert.pem
  copy:
    src: /opt/tls-gen/basic/client/cert.pem
    dest: /opt/MyTApplication/cert_rabbitmq/cert.pem
    remote_src: yes
  when: rabbitmqTLS == "true"

- name: Get key.pem
  copy:
    src: /opt/tls-gen/basic/client/key.pem
    dest: /opt/MyTApplication/cert_rabbitmq/key.pem
    remote_src: yes
  when: rabbitmqTLS == "true"

- name: Get cacert.pem
  copy:
    src: /opt/tls-gen/basic/testca/cacert.pem
    dest: /opt/MyTApplication/cert_rabbitmq/cacert.pem
    remote_src: yes
  when: rabbitmqTLS == "true"

- name: Configure data processing script
  copy:
    src: ../templates/dataProcessing.py
    dest: /opt/MyTApplication/dataProcessing.py

- name: Configure data requirements.txt
  copy:
    src: ../templates/requirements.txt
    dest: /opt/MyTApplication/requirements.txt

- name: Configure config file
  copy:
    src: ../templates/config.ini
    dest: /opt/MyTApplication/config.ini

- name: Configure database connector
  copy:
    src: "/opt/MyTApplication/databaseLibs/{{ database }}.py"
    dest: /opt/MyTApplication/database.py
    remote_src: yes

- name: Configure docker-compose.yml file
  copy:
    src: "../templates/dockerComposeFiles/{{ database }}.yml"
    dest: /opt/MyTApplication/docker-compose.yml

- name: Set Ownership of application to ubuntu
  file:
    path: /opt/MyTApplication
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Build Data Processing Docker image from Dockerfile
  docker_image:
    name: dataprocessing
    build:
      path: /opt/MyTApplication
    state: present
    source: build

- name: Create and start services
  docker_compose:
    project_src: /opt/MyTApplication
  register: output
