---

- name: Remove MyT MyTApplication
  file:
    path: /opt/MyTApplication
    state: absent

- name: Pull MyT git repo
  git:
    repo: https://github.com/Daemon-Macklin/MyTPlatformDataProcessingContainer
    dest: /opt/MyTApplication

- name: Configure data processing script
  copy:
    src: ../templates/dataProcessing.py
    dest: /opt/MyTApplication/dataProcessing.py

- name: Configure data requirements.txt
  copy:
    src: ../templates/requirements.txt
    dest: /opt/MyTApplication/requirements.txt

- name: Configure config file
  copy:
    src: ../templates/config.ini
    dest: /opt/MyTApplication/config.ini

- name: Configure database connector
  copy:
    src: "/opt/MyTApplication/databaseLibs/{{ database }}.py"
    dest: /opt/MyTApplication/database.py
    remote_src: yes

- name: Configure docker-compose.yml file
  copy:
    src: "../templates/dockerComposeFiles/{{ database }}.yml"
    dest: /opt/MyTApplication/docker-compose.yml

- name: Upload influxdb setup script
  copy:
    src: "../templates/setupScripts/{{ database }}.py"
    dest: /opt/MyTApplication/dbSetup.py

- name: Set Ownership of application to ubuntu
  file:
    path: /opt/MyTApplication
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Build Data Processing Docker image from Dockerfile
  docker_image:
    name: dataprocessing
    build:
      path: /opt/MyTApplication
    state: present
    source: build

- name: Create and start services
  docker_compose:
    project_src: /opt/MyTApplication
  register: output

- name: Install docker-py
  pip:
    name: influxdb
  when: database == "influxdb"

- name: Run the db setup script
  command: python3 /opt/MyTApplication/dbSetup.py

- name: Remove influxsetup script
  file:
    path: /opt/MyTApplication/dbSetup.py
    state: absent
