--- 

- name: Generate Dump
  command: docker exec mongodb mongodump --forceTableScan -d MyTData --out /mongodump

- name: Get Dump
  command: docker cp mongodb:/mongodump ~/mongodump
 
- name: Zip Dump
  archive:
    path: ~/mongodump
    dest: ~/mongodump.zip
    format: zip
    remove: yes

- name: Downoad Zip
  fetch:
    flat: yes
    src: ~/mongodump.zip
    dest: ./mongodump.zip

- name: Remove Zip
  file:
    path: ~/mongodump.zip
    state: absent

