---
- hosts: vms
  vars:
    cloudService: 'aws'
    externalVol: '/dev/nvme1n1'
    database: 'influx'
  become: yes
  roles:
  - role: dmacklin.machineSetup
  - role: dmacklin.dockerAnsible
  - role: dmacklin.mytInstall
...
