version: '3.5'
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - myt-network
    container_name: influxdb
    volumes:
      - /var/lib/mytDatabase:/var/lib/influxdb
    environment:
      -  INFLUXDB_DB=MyTData
  broker:
    image: rabbitmq
    hostname: rabbitmq
    networks:
      - myt-network
    ports:
      - "15672:15672"
      - "5672:5672"
    #environment:
      #- RABBITMQ_DEFAULT_USER=guest
      #- RABBITMQ_DEFAULT_PASS=guest
    container_name: rabbitmq
  dataprocessing:
    build: .
    image: dataprocessing
    networks:
      - myt-network
    depends_on:
      - broker
      - influxdb
    restart: on-failure
    container_name: dataprocessing
  grafana:
    image: grafana/grafana
    networks:
      - myt-network
    ports:
      - "3000:3000"
    container_name: grafana
networks:
  myt-network:
    name: myt-network
    driver: bridge