version: '3.5'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - myt-network
    container_name: mongodb
    volumes:
      - /var/lib/mytDatabase:/var/lib/mongodb
    environment:
      - MONGO_INITDB_DATABASE=MyTData
  broker:
    image: rabbitmq
    hostname: rabbitmq
    networks:
      - myt-network
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    #environment:
      #- RABBITMQ_SSL_CERTFILE=/cert_rabbitmq/cert.pem
      #- RABBITMQ_SSL_KEYFILE=/cert_rabbitmq/key.pem
      #- RABBITMQ_SSL_CACERTFILE=/cert_rabbitmq/cacert.pem
      #- RABBITMQ_DEFAULT_USER=guest
      #- RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./cert_rabbitmq:/cert_rabbitmq
    container_name: rabbitmq
  dataprocessing:
    build: .
    image: dataprocessing
    networks:
      - myt-network
    depends_on:
      - broker
      - mongodb
    restart: on-failure
    container_name: dataprocessing
  grafana:
    image: grafana/grafana
    networks:
      - myt-network
    ports:
      - "3000:3000"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-simple-json-datasource"
    container_name: grafana
networks:
  myt-network:
    name: myt-network
    driver: bridge