---

- name: Update and Upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install required packages
  apt: name={{item}} state=present
  with_items:
    - python3-pip
    - zip

- name: Create a ext4 filesystem on attached volume
  filesystem:
    fstype: ext4
    dev: "{{ externalVol }}"

- name: Create a directory to mount the volume
  file:
    path: /var/lib/mytDatabase
    state: directory
    mode: '0755'

- name: Mount and bind a volume
  mount:
    path: /var/lib/mytDatabase
    src: "{{ externalVol }}"
    state: mounted
    fstype: ext4