---

- name: Update and Upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install required packages
  apt: name={{item}} state=present
  with_items:
    - python3-pip
